services:
  - type: web
    name: class-one-savings
    runtime: python
    buildCommand: |
      cd frontend && yarn install && yarn build &&
      mkdir -p ../backend/static &&
      cp -r build/* ../backend/static/ &&
      cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://class_one_db:Buttuura@cluster0.bayp373.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&tls=true&tlsAllowInvalidCertificates=true
      - key: DB_NAME
        value: class_one_savings
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: superadmin@savingsgroup.com
      - key: ADMIN_PASSWORD
        value: SuperAdmin@123
      - key: GOOGLE_SPREADSHEET_ID
        value: 1gbSYI3EOP2L6ZqvL0lWbWKyyqpXK46Y_f9s3F5S34HI
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        value: class-one-savings-group@awesome-habitat-374402.iam.gserviceaccount.com
      - key: GOOGLE_PROJECT_ID
        value: awesome-habitat-374402
      - key: GOOGLE_PRIVATE_KEY_ID
        value: ca1c848f1eab886c1c4dbb21af6d165ac79024af
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: "107913506020948964345"
      - key: CORS_ORIGINS
        value: "*"
